name: 'Terraform Dev Environment'

on:
  pull_request:
    branches: [ develop ]
    paths:
      - 'environments/dev/**.tf'
  push:
    branches: [ develop ]
    paths:
      - 'environments/dev/**.tf'


jobs:
  terraform:
    name: 'Terraform Plan/Apply'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    defaults:
      run:
        working-directory: ./environments/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}   # wif_provider_name output
          service_account: ${{ secrets.GCP_TF_SERVICE_ACCOUNT }}        # tf_org_admin email

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: |
          terraform plan -input=false \
            -var="db_password=${{ secrets.TF_DEV_DB_PASSWORD }}" \
            -out=tfplan
        continue-on-error: true

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: terraform output
